database_url = 'eventz.db'
tezos_rpc_url = 'https://mainnet.tezos.marigold.dev'
enable_sync = true
enable_api = true
sync_block_level_from = -1
blocks_to_check_sync = 10
data_store_mode = 100
smart_contracts = 'all'
